baseURL = "http://eduardoalencar.com"
languageCode = "en-us"
title = "Eduardo Alencar"
theme = "papermod"
# pygmentsCodeFences = true
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

disqusShortname = "eduardoalencar-website" #Disqus shortname
googleAnalytics = "UA-28810177-1" #Google Analytics ID
description = "Desenvolvimento web backend e frontend. Linguagens de programação, PHP, Python, Java, Kotlin, Go, Javascript. Filosofia, reflexões e opiniões."

[params]
author = "Eduardo Alencar"
bio = "Desenvolvedor Web"
description = "Desenvolvedor web com 13 anos de experiência. No backend já trabalhei com PHP, Python, NodeJS, Kotlin e Go, no froentend, além de HTML, CSS e Javascript atuei com ReactJS."
defaultTheme = "dark"
## Set one of:
gravatar = "ealencar10@gmail.com"
#profilePicture = "images/profile.png"

copyright = "Eduardo Alencar"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
#themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/eduardoalencardotcom"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/edueo"
  #
  # [[params.socialIcons]]
  # icon = "fa-twitter"
  # title = "Email"
  # url = "#"
