[params]
author = "Author Name"
description = "My Blog"

## Set one of:
gravatar = "ealencar10@gmail.com"
profilePicture = "images/profile.png"

copyright = "Author Name"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = ""

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/edueo"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"
