dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.83.1
  - secure: wyv9zDKkrzpAkl/ABufbFT3dGjh0c1yiaZeOckh6wOBC4vfL99KhUfo+d/t795J8lnm1yTFgBRoOCM7NBQaPHb6VU9Y2A8mC+REF31c1DdeQcLmeKiIBy2YiinnUW/XldRGzTuf6QZfmPZaUQrHSJBnFBiHwY24Kf/+ycPQKLJthyttWAekzKLC4xXs7QPZziAdPFvmNdaS5VAh8OlYErjCwPKOR07OAK4zNc2lhhF9av4IoH5mkNAr4nrQ6APX8T0NoLESJG8j0FATFjErilns+/DLvw5f5hXAsYK1TGQqUnf4PKDL8QfP+qBqcSAQPT39KWhZIPJe5sUzdWPm4kscuZ5DuAuVKard9Ca9bDXM/FyYPVACvvr20oWzVU7+82ytp/LHeBPIsMfvb1qlJA+2KIS1+9ShYiw4BdbiK6tc5aNRr9dIWGydEKX0TIfhQiS5yuqXWoOEULbjCQxLVfr59pVe//fV7s5CsNV9L//d5w0S9kRA0Sbx3/jWcF9JkcVThtCsShV838XoH2QvCDEZ5qgvBOBn4H8ngaNv1Ma/wOa44pkI1u4mR80kLEKiYxijezAz+MsxHkxx/4vpV4OmviZrhGyGUKS+5gEtWoxtNYD9e80SEXRzHq3vI1oNBYKrTAjipUnIKg6OpiLBVGgAH0OYi3V7Zw7EnlyvsybU=
  - secure: GHDI0jNFconMZG2fM8KzRjwIypwyJ7pU6o1vPBrrVjdAfnO5nx9dSw+vTStRwJUYI5XhTls/NpOAskvRC2aNFFhhIv+Zgch17BpOXKLufjqkP35qOZdt9HQKzpE+LQRkScPARsi36dtpWkHsCFxhD2FmVq4Yq84E49ZO2OlZUQfOOi6wD93llacbwu+/boNUK3qLZyqzjuQPKtGLZFJ49imh1PNLzy+RV754kQHns15z6EmDiJX6YztHJIrudkGMZYJpfMrmCAG+K7qqNSBep0fYajRTsSsj3RKU8d9ELINf5SLuJYJPWY8IpTq/FYOHqomVPoExuUqql3GFYqskhGMg3jvAh/qCtcNts5rKvYnupnjX/nzBGgsRpZPUxtfhbfSoK2wUXlinrWpGYYfgeJkXgLOk4eYivsTv+1sCqi6OM+P/0UhTX/n3pPUBlhBVWJmnaQehnip5R4W8WLeEoEDmVuFYRI4TzEDKv9o8jlgM7yUdes9LQk5bHXVoNpW8iSAzr7h84b7Bau8OmPMVw39YDtEu0pf+EIdqLRFy04fJ9sj0ygNc+2cB5Ip1fq62GRhoecDqd30KrEK2xFsdMT2TK1IThPjNsMh4EMTDZkonLbCzoAHKGBqvj3GKflAQnyB0ldIN5AwV9XUGd4WIqCna7dQzLsRXS6wH7pmacXw=
  - secure: kr4opBA1f5LhDjKSiPg4xAnP1CtKbScIZZfNBL7EU/69J1J46Vou1nWXUYWKWlQCDRM22MIrn2RazwJxgPQvY/11zH1mgWc27TgnPIoYAjAM2OI05vgvYwqZ/6B30y+BIXo3aDkor/CPnJ0/ZA8kjDW36MILMBnUNEn82ckJVp8WXJJo0HuBYDmYFiENaibud66tqV5WGntotL6Bq/Ww/QnGsd0PQMQ2m5pAWJKMSMzhHzZ8qzvMmPvkwPaunC9+zXpRjFiSZpZfXsgQsyIfmzbybNCfNV7M2viAaz1pQTbUecj0Z/SmzTAyu8IeHne/Ztvx8+W3iXLcv73p64bltWkEk8b2HrPCiYp/K73Jm1LTeYs+05J4pVUAE8M9eNzDcmuhTlYjcB23krjK3knTFId/jMagT2K633t9aZZTCW09qRrsO2PJwEL0qznpLldwasPDNrva3DQ8/uU6awb6mll1uZgdMd0B/um00gb8yCtyK3xmeVhDzdpv+JioijKAjed/Nf/2crkj+D54xBiaBS1vyevXpJNXHXZjUWeXHkttXPTkEBPTmO/jhqvojog5IJGM5BK5u7fUgBFLDZSKJGYDpNoylsbxwlx/05cO1U7dPJyLz3FtOvCjkACQw8T4LDw44nWgxMmYXDVZXGngFsurUglfUARVuMrIUp+r/lo=
